### ISSUE TITLE
Docker compose example

### ISSUE THREAD

**Issue by stgreenb** [haijeploeg/excludarr#32]
**Is your feature request related to a problem? Please describe.**
When I try to use the following docker compose:
```
  excludarr:
    container_name: excludarr
    image: haijeploeg/excludarr
    environment:
      - GENERAL_PROVIDERS=netflix,amazon prime video
      - RADARR_URL=http://192.168.1.197:7878
      - RADARR_API_KEY=*REDACTED*
```
I see that an additional command needs to be issued, see logs: 
```
Usage: excludarr [OPTIONS] COMMAND [ARGS]...
Try 'excludarr --help' for help.

Error: Missing command.
Container stopped
```
**Describe the solution you'd like**
Docker compose yml example.  BTW, you have a compose example in github, but its only for sonarr and radarr. 

**Describe alternatives you've considered**
See above.
