### ISSUE TITLE
Excludarr is processing TV series indicated in SONARR_EXCLUDE env variable

### ISSUE THREAD

**Issue by andrefpina** [haijeploeg/excludarr#86]
**Describe the bug**
Excludarr is not excluding TV series indicated in the SONARR_EXCLUDE environment variable from being processed. However, it works perfectly for movies indicated in the RADARR_EXCLUDE variable.

**To Reproduce**
1. `docker compose -f excludarr.yml run excludarr --debug sonarr exclude -a delete -d -e --progress` where the relevant part of `excludarr.yml` is:
```
version: "3.6"
services:
  excludarr:
    image: haijeploeg/excludarr
    container_name: excludarr
    environment:
      GENERAL_FAST_SEARCH: "true"
      GENERAL_LOCALE: "pt_PT"
      GENERAL_PROVIDERS: "Disney Plus, HBO Max, Amazon Prime Video"
      RADARR_URL: "https://*****.***/radarr"
      RADARR_API_KEY: "**************************"
      RADARR_VERIFY_SSL: "false"
      RADARR_EXCLUDE: '"The Lord of the Rings: The Fellowship of the Ring", "The Lord of the Rings: The Two Towers", "The Lord of the Rings: The Return of the King", "Avatar"'
      SONARR_URL: "https://*****.***/sonarr"
      SONARR_API_KEY: "**************************"
      SONARR_VERIFY_SSL: "false"
      SONARR_EXCLUDE: '"Andor", "The Mandalorian"'
      CRON_MODE: "false"
    volumes:
      - /home/admin/docker/excludarr/crontab:/etc/excludarr/crontab
    restart: unless-stopped
```
I have tried using both array syntax and map syntax for the environment variables, as stated in [Docker Docs](https://docs.docker.com/compose/compose-file/05-services/#environment), without success.
I have also tried to run excludarr as `docker run -it --rm --env-file excludarr.env haijeploeg/excludarr:latest sonarr exclude -a delete -d -e --progress` having the environment variables in `excludarr.env`, but the problem persisted.

**Expected behavior**
I would expect both "Andor" and "The Mandalorian" to be ignored.

**Versions**
I'm using the latest Docker tag as of 2023-04-24.

**Debug logging**
[Excludarr debug log](https://gist.github.com/andrefpina/513fc4f98c70d5b1d3bcea0fb977a654)
